sudo: false
language: python
python:
    - '3.5'
# command to install dependencies
install: "pip install -U tox"
# # command to run tests
env:
  matrix:
    # coveralls is not listed in tox's envlist, but should run in travis
    #- TESTENV=coveralls
    # note: please use "tox --listenvs" to populate the build matrix below
    - TESTENV=linting
    - TESTENV=py35
    - TESTENV=doctesting

script: tox --recreate -e $TESTENV